### ISSUE TITLE
Typo error in Footer

### ISSUE THREAD

**Issue by mihirpaldhikar** [mihirpaldhikar/pu-convocation#2]
https://github.com/mihirpaldhikar/pu-convocation/blob/449018f5e736897ed2fdf9e63b4bdf39051ac409/frontend/websites/puconvocation-com/src/components/footer.tsx#L42

Please fix the typo error in "We We Are". The intended text should be "Who We Are"

**Comment by Suhani-013** [comment]
on it ..ill make a branch alag se and do it usee ..ive been meaning to do
this for a while now

**Comment by mihirpaldhikar** [comment]
Any updates on the progress?
